run:
  deadline: 2m
  skip-files: []

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: 80
    statements: 50
  godox:
    keywords:
      - FIXME

linters:
  enable-all: true
  disable:
    - maligned
    - lll
    - dupl
    - wsl
    - nlreturn
    - gomnd
    - goerr113
    - wrapcheck
    - exhaustivestruct
    - testpackage
    - tparallel
    - paralleltest
    - ifshort
    - scopelint
    - prealloc
    - exhaustive
    - cyclop

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'ST1000: at least one file in a package should have a package comment'
  exclude-rules:
    - path: .*_test.go
      linters:
        - funlen
        - unused
