run:
  deadline: 10m
  skip-files: [ ]
  skip-dirs:
    - pkg/crd/generated

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  goconst:
    min-len: 5
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: 80
    statements: 50
  godox:
    keywords:
      - FIXME
  gofumpt:
    extra-rules: true
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/sirupsen/logrus
      - github.com/pkg/errors
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - sloppyReassign
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine # already handle by gofumpt.extra-rules
      - unnamedResult
    settings:
      hugeParam:
        sizeThreshold: 100
#  ifshort:
#    max-decl-lines: 1
#    max-decl-chars: 20
  importas:
    # Standard Kubernetes rewrites:
    corev1: "k8s.io/api/core/v1"
    netv1: "k8s.io/api/networking/v1"
    netv1beta1: "k8s.io/api/networking/v1beta1"
    admv1: "k8s.io/api/admission/v1"
    admv1beta1: "k8s.io/api/admission/v1beta1"
    extv1beta1: "k8s.io/api/extensions/v1beta1"
    metav1: "k8s.io/apimachinery/pkg/apis/meta/v1"
    ktypes: "k8s.io/apimachinery/pkg/types"
    kerror: "k8s.io/apimachinery/pkg/api/errors"
    clientset: "k8s.io/client-go/kubernetes"
    kubemock: "k8s.io/client-go/kubernetes/fake"
    # Traefik Kubernetes rewrites:
    traefikv1alpha1: "github.com/traefik/neo-agent/pkg/crd/api/traefik/v1alpha1"
    traefikclientset: "github.com/traefik/neo-agent/pkg/crd/generated/client/traefik/clientset/versioned"
    traefikinformer: "github.com/traefik/neo-agent/pkg/crd/generated/client/traefik/informers/externalversions"
    traefikkubemock: "github.com/traefik/neo-agent/pkg/crd/generated/client/traefik/clientset/versioned/fake"
    # Neo Kubernetes rewrites:
    neov1alpha1: "github.com/traefik/neo-agent/pkg/crd/api/neo/v1alpha1"
    neoclientset: "github.com/traefik/neo-agent/pkg/crd/generated/client/neo/clientset/versioned"
    neoinformer: "github.com/traefik/neo-agent/pkg/crd/generated/client/neo/informers/externalversions"
    neokubemock: "github.com/traefik/neo-agent/pkg/crd/generated/client/neo/clientset/versioned/fake"
    # Misc:
    jwtreq: "github.com/dgrijalva/jwt-go/request"

linters:
  enable-all: true
  disable:
    - maligned # deprecated
    - interfacer # deprecated
    - scopelint # deprecated
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - cyclop # duplicate of gocyclo
    - lll
    - dupl
    - wsl
    - nlreturn
    - gomnd
    - goerr113
    - wrapcheck
    - exhaustive
    - exhaustivestruct
    - testpackage
    - tparallel
    - paralleltest
    - prealloc
    - forcetypeassert
    - bodyclose # Too many false positives: https://github.com/timakin/bodyclose/issues/30
    - ifshort # disable due to false-positive, the linter will be fixed https://github.com/esimonov/ifshort

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'ST1000: at least one file in a package should have a package comment'
    - 'G204: Subprocess launched with variable'
    - 'G304: Potential file inclusion via variable'
  exclude-rules:
    - path: .*_test.go
      linters:
        - funlen
        - unused
    - path: pkg/crd/api/.*/v1alpha1/register.go
      linters:
        - gochecknoglobals
    - path: pkg/acp/admission/reviewer/reviewer.go
      linters:
        - goconst
    - path: pkg/acp/admission/reviewer/nginx_ingress_snippet.go
      linters:
        - gosec
    - path: pkg/metrics/protocol/protocol.go
      text: '[[:alpha:]]+V\dSchema is a global variable'
